In [69]:
with open('One.txt') as mytext:
    words_one = mytext.read().lower().split()
    uni_words_one = set(words_one)

In [70]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [71]:
with open('Two.txt') as Mytext:
    words_two = Mytext.read().lower().split()
    uni_words_two = set(words_two)

In [72]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [73]:
all_uni_words = set()
all_uni_words.update(uni_words_one)

In [74]:
all_uni_words.update(uni_words_two)

In [75]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [76]:
full_vocab = dict()
i = 0

for word in all_uni_words:
    full_vocab[word] = i
    i = i+1;

In [77]:
full_vocab

{'dogs': 0,
 'our': 1,
 'pets': 2,
 'water': 3,
 'are': 4,
 'surfing': 5,
 'about': 6,
 'popular': 7,
 'animals': 8,
 'catching': 9,
 'furry': 10,
 'canine': 11,
 'waves': 12,
 'story': 13,
 'fun': 14,
 'sport': 15,
 'this': 16,
 'is': 17,
 'a': 18}

In [78]:
one_freq = [0]*len(full_vocab)
two_freq = [0]*len(full_vocab)
all_words = ['']*len(full_vocab)

In [79]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [80]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [81]:
with open('One.txt') as f:
    one_text = f.read().lower().split()

In [82]:
one_text

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [83]:
for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind] += 1

In [84]:
one_freq

[2, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1]

In [85]:
with open('Two.txt') as f:
    Two_text = f.read().lower().split()

In [86]:
Two_text

['this',
 'story',
 'is',
 'about',
 'surfing',
 'catching',
 'waves',
 'is',
 'fun',
 'surfing',
 'is',
 'a',
 'popular',
 'water',
 'sport']

In [87]:
for word in Two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind] += 1

In [88]:
two_freq

[0, 0, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 3, 1]

In [89]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [90]:
for word in full_vocab:
    word_ind = full_vocab[word]
    all_words[word_ind] = word

In [91]:
all_words

['dogs',
 'our',
 'pets',
 'water',
 'are',
 'surfing',
 'about',
 'popular',
 'animals',
 'catching',
 'furry',
 'canine',
 'waves',
 'story',
 'fun',
 'sport',
 'this',
 'is',
 'a']

In [92]:
import pandas as pd
bow = pd.DataFrame(data = [one_freq,two_freq],columns = all_words)

In [93]:
bow

dogs  our  pets  water  are  surfing  about  popular  animals  catching  \
0     2    1     1      0    1        0      1        0        1         0   
1     0    0     0      1    0        2      1        1        0         1   

   furry  canine  waves  story  fun  sport  this  is  a  
0      1       1      0      1    0      0     1   1  1  
1      0       0      1      1    1      1     1   3  1

In [94]:
text = ['This is a line',
       'This is anothre line',
       'Completely Different line']

In [108]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [109]:
help(CountVectorizer)

Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |  
 |  Convert a collection of text documents to a matrix of token counts
 |  
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |  
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |  
 |  Read more in the :ref:`User Guide <text_feature_extraction>`.
 |  
 |  Parameters
 |  ------

In [116]:
cv = CountVectorizer()

In [117]:
sparse_matrix = cv.fit_transform(text)

In [118]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [119]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'anothre': 0, 'completely': 1, 'different': 2}

In [120]:
tfidf = TfidfTransformer()

In [121]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [125]:
results = tfidf.fit_transform(sparse_matrix) ## BOW ----> TF-IDF

In [126]:
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [127]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [128]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [129]:
tv = TfidfVectorizer()

In [131]:
tv_results = tv.fit_transform(text)

In [134]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])